### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by lm8** [Ponup/thiefcatcher#1]
Is there a license for this program?  Looks really cute.  I know a couple of Linux game distributions that might be interested in adding it if it's under an OSI approved license of some kind.

**Comment by lm8** [comment]
Okay, found the License.txt file under the Core directory.  Sorry for the unnecessary post.  It mentions in the CREDITS.txt file that you have ideas to improve the game and might want help.  Looks like a nice game with a lot of potential.  I'd be interested in helping out if you still need volunteers.  I can code C/C++ and am familiar with SDL2 and SDL.

**Comment by santiagolizardo** [comment]
Hi @lm8 . Thanks for your message. I would like to be helped on this game. I have lot of ideas but unfortunately no much time to make them happen. That could change with another developer in the project.
Just take a look around, compile the project, run it and take something that doesn't work quite well to start.
Thanks!

**Comment by lm8** [comment]
On Thu, August 20, 2015 2:55 pm, Santiago Lizardo wrote:
> I would like to be helped on this
> game. I have lot of ideas but unfortunately no much time to make them
> happen. That could change with another developer in the project. Just take
> a look around, compile the project, run it and take something that
> doesn't work quite well to start. Thanks!

I have it compiled and was testing it out.  I'll look into to modifying a
few things and send you the code if I come up with anything useful.

Best wishes.
Laura
http://www.distasis.com
