### ISSUE TITLE
high sierra - can't resolve sd2 frameworks. 'SDL_mixer.h' file not found

### ISSUE THREAD

**Issue by johndpope** [Ponup/thiefcatcher#3]
problem is a rabbit hole - at the root - I couldn't get SDL2 working - the paths couldn't resolve. think I need to export some env  - I tried dropping in the frameworks into kangaroo folder to no avail. https://stackoverflow.com/questions/19160469/what-happened-to-sdl-mixer-h

**Comment by johndpope** [comment]
did try to do brew install sdl2 / sdl2_mixer but it get's stuck with the include sdl_mixer
#include <SDL/SDL_mixer.h>

**Comment by johndpope** [comment]
brew install sdl2
brew install  SDL2_ttf
brew install  TINYXML2


cmake . && make
-- The CXX compiler identification is AppleClang 10.0.0.10001025
-- Check for working CXX compiler: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating project files for 'ThiefCatcher' version 0.9.9
-- Compiling under Darwin
-- Found Sqlite3 header file in /usr/include
-- Found Sqlite3 libraries: /usr/lib/libsqlite3.dylib
-- Failed to find Gettext libintl (missing: Intl_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/johndpope/Documents/gitWorkspace/thiefcatcher
Scanning dependencies of target kangaroo
[  1%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/Area.cpp.o
[  2%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/Color.cpp.o
[  3%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/CoreService.cpp.o
[  4%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/Database.cpp.o
[  5%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/DialogFactory.cpp.o
[  7%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/Dimension.cpp.o
[  8%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/EventHandler.cpp.o
[  9%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/FileUtlis.cpp.o
[ 10%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/Font.cpp.o
[ 11%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/FontManager.cpp.o
[ 13%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/FontService.cpp.o
[ 14%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/FrameRegulator.cpp.o
[ 15%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/HttpClient.cpp.o
[ 16%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/MathUtil.cpp.o
[ 17%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/MediaManager.cpp.o
In file included from /Users/johndpope/Documents/gitWorkspace/thiefcatcher/Kangaroo/src/MediaManager.cpp:1:
In file included from /Users/johndpope/Documents/gitWorkspace/thiefcatcher/Kangaroo/include/MediaManager.h:6:
/Users/johndpope/Documents/gitWorkspace/thiefcatcher/Kangaroo/include/MediaSound.h:3:10: fatal error:
      'SDL_mixer.h' file not found
#include <SDL_mixer.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [Kangaroo/CMakeFiles/kangaroo.dir/src/MediaManager.cpp.o] Error 1
make[1]: *** [Kangaroo/CMakeFiles/kangaroo.dir/all] Error 2
make: *** [all] Error 2

**Comment by johndpope** [comment]
<img width="773" alt="screen shot 2018-06-30 at 20 08 40" src="https://user-images.githubusercontent.com/289994/42129937-6ce79afe-7ca1-11e8-852a-d789ea132b3e.png">

**Comment by santiagolizardo** [comment]
In my system the SDL_mixer is installed to 
```
/usr/local/Cellar/sdl2_mixer/2.0.2_3/include/SDL2/SDL_mixer.h
/usr/local/include/SDL2/SDL_mixer.h
```
Can you search in your Macos and confirm brew installed the library there as well?
Thanks

**Comment by johndpope** [comment]
so I have a few machines / one was using majove - and think that had wrong mixer - the sdl2 mixer won't intsall.


I'm back on high sierra - have done a clean checkout - thanks for updates to kangaroo. 

so finally have it building - but had to add following

-- Build files have been written to: /Users/jpope/Documents/gitWorkspace/thiefcatcher
[  1%] Building CXX object Kangaroo/CMakeFiles/kangaroo.dir/src/Surface.cpp.o
/Users/jpope/Documents/gitWorkspace/thiefcatcher/Kangaroo/src/Surface.cpp:7:10: fatal error: 'SDL2_rotozoom.h' file not found
#include <SDL2_rotozoom.h>

this is resolved using 
### brew install SDL2_gfx


Scanning dependencies of target ThiefCatcher
[ 45%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/Main.cpp.o
[ 46%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/Vars.cpp.o
[ 47%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/Clue.cpp.o
[ 48%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/ClueManager.cpp.o
[ 50%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/CountriesManager.cpp.o
[ 51%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/Country.cpp.o
[ 52%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/Criminal.cpp.o
[ 53%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/CriminalsManager.cpp.o
[ 54%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/Place.cpp.o
[ 55%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/PlacesManager.cpp.o
[ 57%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/Player.cpp.o
[ 58%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/PlayerCase.cpp.o
[ 59%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/PlayerCaseManager.cpp.o
[ 60%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/PlayersManager.cpp.o
[ 61%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/entities/format/CriminalFormatter.cpp.o
[ 63%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/AssignmentScreen.cpp.o
[ 64%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/ComputerScreen.cpp.o
[ 65%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/CountryDrawing.cpp.o
[ 66%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/DossierScreen.cpp.o
[ 67%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/Game.cpp.o
[ 69%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/GameOverScreen.cpp.o
[ 70%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/HallOfFameScreen.cpp.o
[ 71%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/HelpScreen.cpp.o
[ 72%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/IntroScreen.cpp.o
[ 73%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/Map.cpp.o
[ 75%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/MenuScreen.cpp.o
[ 76%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/OptionsScreen.cpp.o
[ 77%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/PlaceSelector.cpp.o
[ 78%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/ProfileScreen.cpp.o
[ 79%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/screens/handlers/GameEventHandler.cpp.o
[ 80%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/ui/Clock.cpp.o
[ 82%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/ui/widgets/InputBox.cpp.o
[ 83%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/ui/widgets/Menu.cpp.o
[ 84%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/ui/widgets/MenuItem.cpp.o
[ 85%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/ui/widgets/SquareButton.cpp.o
[ 86%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/utilities/Configurator.cpp.o
[ 88%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/utilities/DateTime.cpp.o
[ 89%] Building CXX object Core/CMakeFiles/ThiefCatcher.dir/src/utilities/Translator.cpp.o
/Users/jpope/Documents/gitWorkspace/thiefcatcher/Core/src/utilities/Translator.cpp:5:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [Core/CMakeFiles/ThiefCatcher.dir/src/utilities/Translator.cpp.o] Error 1
make[1]: *** [Core/CMakeFiles/ThiefCatcher.dir/all] Error 2
make: *** [all] Error 2



https://stackoverflow.com/questions/11370684/what-is-libintl-h-and-where-can-i-get-it

**brew reinstall gettext**
**brew unlink gettext && brew link gettext --force** < this was needed to get it all working.

**Comment by johndpope** [comment]
<img width="720" alt="screen shot 2018-07-02 at 12 37 27 pm" src="https://user-images.githubusercontent.com/289994/42175783-b414ee14-7df4-11e8-8d37-b3ec565dd4a8.png">


when i click on the binary - it automatically closes. will investigate and open another ticket
